# Generated by Django 5.1.2 on 2024-10-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_pub', models.DateField()),
                ('desc', models.TextField()),
                ('cantidad_copias', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='images/')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
